name: Java CI with Maven - Automation Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest  # ✅ Changed OS to Windows

    steps:
    # Checkout code
    - uses: actions/checkout@v4

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Build and Install Dependencies
    - name: Build and Install Dependencies
      run: mvn clean install -DskipTests

    # Run Automation Tests
    - name: Run Tests
      run: mvn test

    # Install Allure CLI (Windows)
    - name: Install Allure CLI
      run: |
        Invoke-WebRequest -Uri https://github.com/allure-framework/allure2/releases/download/2.19.0/allure-2.19.0.zip -OutFile allure.zip
        Expand-Archive allure.zip -DestinationPath C:\allure
        echo "C:\allure\allure-2.19.0\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
      shell: powershell

    # Generate Allure Report using CLI
    - name: Generate Allure Report
      run: |
        allure generate target/allure-results -o allure-report --clean
      env:
        ALLURE_RESULTS_DIR: target/allure-results
        ALLURE_REPORT_DIR: allure-report

    # Upload Allure Report as Artifact
    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report

    # Upload Extent Report (Ensure correct path)
    - name: Upload Extent Report
      uses: actions/upload-artifact@v4
      with:
        name: extent-report
        path: reports/ExtentReports  # ✅ Updated to the correct expected path
